// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATLpjwvdX6l_e_oeHiDJBAs6Bsj6q-R4s',
    appId: '1:711400431988:web:7cc25a0b35025e57708c21',
    messagingSenderId: '711400431988',
    projectId: 'jgr-int',
    authDomain: 'jgr-int.firebaseapp.com',
    storageBucket: 'jgr-int.appspot.com',
    measurementId: 'G-L5NYTFHY3Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5Z8xCwNOAPmu915gItYpZx5nsJc4hE9g',
    appId: '1:711400431988:android:1b7778c1c265ca7f708c21',
    messagingSenderId: '711400431988',
    projectId: 'jgr-int',
    storageBucket: 'jgr-int.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-_3LAL1RlMs7xrz90frCRZLWTU_GfMXQ',
    appId: '1:711400431988:ios:32937fc27d7df716708c21',
    messagingSenderId: '711400431988',
    projectId: 'jgr-int',
    storageBucket: 'jgr-int.appspot.com',
    iosBundleId: 'com.jjunguri.dksh203',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-_3LAL1RlMs7xrz90frCRZLWTU_GfMXQ',
    appId: '1:711400431988:ios:ffe6b07dcad3c6ac708c21',
    messagingSenderId: '711400431988',
    projectId: 'jgr-int',
    storageBucket: 'jgr-int.appspot.com',
    iosBundleId: 'com.jjunguri.dksh203.RunnerTests',
  );
}
